server:
    port: 10020
spring:
    application:
        name: zk-service
    cloud:
        zookeeper:
            connect-string: localhost:2181
        discovery:
            enabled: true
            register: true
